# Generated by Django 2.2.10 on 2020-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_verifying_agent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(default='', help_text='Gender Identity', max_length=64),
        ),
    ]
