# Generated by Django 2.2.10 on 2020-08-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200826_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verifying_agent_email',
        ),
    ]
