# Generated by Django 2.2.10 on 2020-08-26 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_source', models.CharField(blank=True, default='https://nwt-staging.azurehealthcareapis.com/', max_length=512)),
                ('fhir_patient_id', models.CharField(blank=True, default='', max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_identifier', models.CharField(blank=True, default='', max_length=120)),
                ('user_id_type', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'user_identifier')},
            },
        ),
    ]
