# Generated by Django 2.2.13 on 2021-01-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientface_api', '0003_auto_20210114_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientface_crosswalk_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
