# Generated by Django 2.2.13 on 2021-01-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth2_provider', '0002_auto_20190406_1805'),
        ('dot_ext', '0024_auto_20210115_1813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccessToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oauth2_provider.accesstoken',),
        ),
        migrations.CreateModel(
            name='MyApplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.application',),
        ),
        migrations.CreateModel(
            name='MyAuthFlowUuid',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.authflowuuid',),
        ),
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fhir_id', models.CharField(db_column='fhir_id', db_index=True, default=None, max_length=80, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id_type', models.CharField(choices=[('H', 'HICN'), ('M', 'MBI')], default='H', max_length=1, verbose_name='Hash ID type last used for FHIR_ID lookup')),
                ('_user_id_hash', models.CharField(db_column='user_id_hash', db_index=True, default=None, max_length=64, unique=True, verbose_name='HASH of User HICN ID')),
                ('_user_mbi_hash', models.CharField(db_column='user_mbi_hash', db_index=True, default=None, max_length=64, null=True, unique=True, verbose_name='HASH of User MBI ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
