# Generated by Django 2.2.13 on 2021-01-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedDataAccessGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('beneficiary', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['beneficiary', 'application'], name='authorizati_benefic_ed2194_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['beneficiary'], name='authorizati_benefic_1d71fe_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['application'], name='authorizati_applica_d92033_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataaccessgrant',
            unique_together={('beneficiary', 'application')},
        ),
        migrations.AddIndex(
            model_name='archiveddataaccessgrant',
            index=models.Index(fields=['beneficiary'], name='authorizati_benefic_27dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveddataaccessgrant',
            index=models.Index(fields=['application'], name='authorizati_applica_2616e8_idx'),
        ),
    ]
