# Generated by Django 2.2.10 on 2020-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hie', '0003_auto_20200508_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hieprofile',
            name='organization_name',
            field=models.CharField(blank=True, default='OAuth2.org', max_length=64),
        ),
    ]
